name: Linters

on:
  pull_request:

permissions:
  contents: read

jobs:
  semgrep:
    name: Semgrep
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Download Frappe Semgrep rules
        run: git clone --depth 1 https://github.com/frappe/semgrep-rules.git frappe-semgrep-rules

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep ci --config ./frappe-semgrep-rules/rules --config r/python.lang.correctness
